### ISSUE TITLE
Not in npm registry

### ISSUE THREAD

**Issue by maheshcharig** [lalalilo/express-crud-router-sequelize-v6-connector#2]
'express-crud-router-sequelize-v6-router@1.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by urakozz** [comment]
There is a type in docs, use `express-crud-router-sequelize-v6-connector`

**Comment by nicgirault** [comment]
Sorry for the delay to answer. This lib was poorly maintained until now. Thanks for reporting. I Fixed the typo.
