### ISSUE TITLE
Documentation misleading?

### ISSUE THREAD

**Issue by shousper** [lalalilo/express-crud-router-sequelize-v6-connector#3]
Contrary to the README.md, `sequelizeSearchFields` is not exported from the root of the package currently, and must be imported from `lib/searchList`.

Please export what should be available from the root of the package from it's `index.ts` 🙏🏻

**Comment by nicgirault** [comment]
Sorry for the delay to answer. This lib was poorly maintained until now. Thanks for reporting. I Fixed this issue by correctly exporting the helper functions
